baseurl: /
languageCode: en-US
title: L'Atelier des embruns
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.gitignire
  - \.Rprofile
  - \.Rhistory
  - \.RData
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - pageRef: /
      name: Accueil
      url:
      weight: 10
    - pageRef: about
      name: Qui suis-je?
      url: /about/
      weight: 20
    - pageRef: aquarelles 
      name: Aquarelles
      url: /aquarelles/
      weight: 30
    - pageRef: /paysage/
      name: Paysages
      url: /aquarelles/paysages
      parent: Aquarelles
      weight: 31  
    - pageRef: contact
      name: Contact
      url: /contact/ 
      weight: 40
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: "L'atelier des embruns, aquarelles insiprées par la nature"
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  footer: "&copy; L'atelier des embruns by [Marion Couëdel](https://https://www.instagram.com/seas_sewing/) 2023"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
assetDir: static