baseurl: https://atelier-des-embruns.netlify.app/
languageCode: en-US
title: L'Atelier des embruns - Illustrations à l'aquarelle
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.gitignire 
  - \.Rprofile
  - \.Rhistory
  - \.RData
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - pageRef: /
      name: Accueil
      url:
      weight: 10
    - pageRef: about
      name: Qui suis-je ?
      url: /about/
      weight: 20
    - pageRef: /aquarelles/ 
      name: Aquarelles
      url: /aquarelles/
      weight: 30
    - pageRef: /naturalistes/
      name: Illustrations naturalistes
      url: /aquarelles/naturalistes
      parent: Aquarelles
      weight: 31
    - pageRef: /paysage/ 
      name: Paysages
      url: /aquarelles/paysages 
      parent: Aquarelles
      weight: 32 
    - pageRef: /carnet/ 
      name: Carnets de voyages
      url: /aquarelles/carnet_voyage 
      parent: Aquarelles
      weight: 33 
    - pageRef: /affiches/ 
      name: Affiches
      url: /aquarelles/affiches 
      parent: Aquarelles
      weight: 34 
    - pageRef: /faire-parts/ 
      name: Papeterie
      url: /aquarelles/faire-parts 
      parent: Aquarelles
      weight: 35 
    - pageRef: /localities/
      name: Par localité
      url: /localities/
      parent: Aquarelles 
      weight: 39
    - pageRef: /categories/
      name: Par catégories
      url: /categories/ 
      parent: Aquarelles
      weight: 38
    - pageRef: Commissions 
      name: Commissions
      url: /Commissions/
      weight: 40
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5 
  description: "Découvrez mes illustration à l'aquarelle, dédié à la beauté naturelle. Explorez une collection d'œuvres captivantes où la nature prend vie à travers des paysages, des fleurs et des animaux, peints avec une sensibilité artistique unique. Laissez-vous inspirer par la magie de l'aquarelle et de la nature."
  SiteDescription: "Découvrez mes illustration à l'aquarelle, dédié à la beauté naturelle. Explorez une collection d'œuvres captivantes où la nature prend vie à travers des paysages, des fleurs et des animaux, peints avec une sensibilité artistique unique. Laissez-vous inspirer par la magie de l'aquarelle et de la nature."
  favicon: favicon.ico 
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: /logo.png
    width: 50 
  footer: "Merci de respecter mon travail, l'ensemble des images est soumis à droit d'auteur: &copy; L'atelier des embruns par [Marion Couëdel](https://https://www.instagram.com/seas_sewing/) 2024"
  contact:
    instagram: "atelier_des_embruns"
    facebook: "latelierdesembruns"
    color: "#a20c4c"
  share:
    color: "#2c4650" 
markup:  
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
assetDir: static 
taxonomies:
  categories: "categories"
  localities: "localities"
  series: "series"
sitemap:
  changeFreq: "monthly"
  disable: false
  filename: sitemap.xml
  priority: -1  
